### ISSUE TITLE
GetUsersByName is way too slow for large user tables

### ISSUE THREAD

**Issue by popstarfreas** [ProfessorXZ/UserSpecificFunctions#2]
I used this plugin on a MySQL database with a user table with around 244,000 entries on a server external to the MySQL server (different machine) and the function always errored out because it took too long to respond with data:

`MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.FetchDataRow(Int32 statementId, Int32 columns)
   at MySql.Data.MySqlClient.Driver.FetchDataRow(Int32 statementId, Int32 columns)
   at MySql.Data.MySqlClient.ResultSet.GetNextRow()
   at MySql.Data.MySqlClient.ResultSet.NextRow(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlDataReader.Read()
   at MySql.Data.MySqlClient.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
   at MySql.Data.MySqlClient.MySqlDataReader.Read()
   at TShockAPI.DB.UserManager.GetUsers()`

Which then causes 
`System.NullReferenceException: Object reference not set to an instance of an object.
   at UserSpecificFunctions.Utils.GetUsersByName(String userName)
   at UserSpecificFunctions.USFCommands.USFPermission(CommandArgs args)`

That error is related because the GetUsersByName in Utils uses TShock.Users.GetUsers(). With my personal version I simply used exact name query rather than loading them all. I think even using a query with LIKE will be slow.

This was on an older version, but as far as I can tell, that function is still used and is unchanged since, and even with async and Tasks it will still timeout and never return.

**Comment by ProfessorXZ** [comment]
Ah, so it breaks. I can't say I didn't see it coming though. The main issue with this is TShock has no memory that we could access to make parsing faster. Ideally, User objects would be stored in a collection, making everything much faster. I'll go with exact name searching for now, and probably implement something a bit better later on.

Thanks for the report :)

**Comment by popstarfreas** [comment]
The problem is, this query can never complete on a large table unless the timeout is changed. So you have no query way of getting every user to then store in a collection for faster searching. It is possible to use an indexer and search engine server like Sphinx to have a query for searching. For example, on Phase (my real-time communication app) I use Sphinx to provide auto-complete in real-time (it's really fast) shown here. However if you find a better way that doesn't require this, that is great: ![example](http://puu.sh/q70en/f1e58f36cd.png)

**Comment by ProfessorXZ** [comment]
@popstarfreas Would you mind testing [3e13a9d](https://github.com/ProfessorXZ/UserSpecificFunctions/commit/3e13a9d970a2d996e71d0affee3048eb775eb040)? This may not be the best solution, but it should improve the performance by a little bit. It will now match `User`s based on the username. The longer the search string the faster the results will come.

**Comment by popstarfreas** [comment]
I've not actually tested this yet, but I ran a LIKE query based on GetUsersByName on my large user table and it performs better than I thought it would. Most of the queries ran in <= 0.5s and returned <= 400 rows. So by those numbers I don't expect the timeout would be reached.
